import { awaitProductTextures } from '../src/products/loading.ts';
import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { createCap } from '../src/products/caps/index.ts';
import { createShoe } from '../src/products/shoes/index.ts';
import { createGarment } from '../src/products/clothes/index.ts';

const params = new URLSearchParams(location.search);
const category = params.get('category') ?? 'caps';
const index = Number(params.get('index') ?? 0);
const factories = { caps: createCap, shoes: createShoe, clothes: createGarment };
if (!Object.hasOwn(factories, category)) throw new Error(`Unknown category ${category}`);
const product = factories[category](index);
const scene = new THREE.Scene();
scene.background = new THREE.Color('#e8e8e5');
scene.add(product, new THREE.HemisphereLight('#ffffff', '#a4a2a0', 2.6));
const key = new THREE.DirectionalLight('#ffffff', 3.4);
key.position.set(-2, 4, 5);
scene.add(key);
const fill = new THREE.DirectionalLight('#ffffff', 1.4);
fill.position.set(3, 2, -4);
scene.add(fill);
const renderer = new THREE.WebGLRenderer({ antialias: true, preserveDrawingBuffer: true });
renderer.setPixelRatio(1);
renderer.setSize(innerWidth, innerHeight);
renderer.outputColorSpace = THREE.SRGBColorSpace;
renderer.toneMapping = THREE.ACESFilmicToneMapping;
document.body.append(renderer.domElement);
const bounds = new THREE.Box3().setFromObject(product);
const center = bounds.getCenter(new THREE.Vector3());
const size = bounds.getSize(new THREE.Vector3());
const camera = new THREE.PerspectiveCamera(32, innerWidth / innerHeight, .001, 100);
const distance = Math.max(size.x / camera.aspect, size.y, size.z) / (2 * Math.tan(THREE.MathUtils.degToRad(16))) * 1.35;
const directions = { offaxis: [.9, .4, 1], rear: [0, .08, -1], rearOblique: [-.9, .4, -1], right: [1, .08, 0] };
const direction = new THREE.Vector3(...(directions[params.get('angle')] ?? [0, category === 'caps' ? .45 : .08, 1]));
camera.position.copy(center).addScaledVector(direction.normalize(), distance);
camera.lookAt(center);
await awaitProductTextures();
const meshes = [];
product.traverse(object => {
  if (!object.isMesh) return;
  const materials = Array.isArray(object.material) ? object.material : [object.material];
  meshes.push({ name: object.name, vertices: object.geometry.getAttribute('position')?.count, materials: materials.map(material => ({ userData: material.userData, color: material.color?.getHexString(), map: material.map ? { url: material.map.image?.currentSrc ?? material.map.image?.src, width: material.map.image?.width, height: material.map.image?.height, version: material.map.version } : null })) });
});
await renderer.compileAsync(scene, camera);
renderer.render(scene, camera);
const controls = new OrbitControls(camera, renderer.domElement);
controls.target.copy(center);
controls.minDistance = distance * .4;
controls.maxDistance = distance * 2;
controls.update();
controls.addEventListener('change', () => renderer.render(scene, camera));
await new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(re