import assert from 'node:assert/strict';
import { evidence, launch, layout, url } from './qa-support.mjs';
const ev = await evidence(process.env.MLB_WALK_STAGE ?? 'walk-final');
const browser = await launch();
ev.report.browser.version = browser.version();
const context = await browser.newContext({ viewport: { width: 1280, height: 900 } });
const page = await context.newPage();
ev.watch(page);
const state = () => page.evaluate(() => window.__MLB_DEBUG__);
const ready = () => page.waitForFunction(() => window.__MLB_DEBUG__?.sceneReady && window.__MLB_DEBUG__.cameraSettled);
const capture = async name => ev.capture(page, name, await state());
const check = (name, pass, detail = {}) => { ev.report.checks.push({ name, pass, ...detail }); assert.ok(pass, name); };
const distance = (a, b) => Math.hypot(...a.map((v, i) => v - b[i]));
async function move(key, meters = .15) {
  const before = (await state()).navigation.position;
  await page.keyboard.down(key);
  await page.waitForFunction(({ before, meters }) => Math.hypot(...window.__MLB_DEBUG__.navigation.position.map((v, i) => v - before[i])) >= meters, { before, meters }, { timeout: 5000 });
  await page.keyboard.up(key);
  await page.waitForFunction(() => !window.__MLB_DEBUG__.navigation.moving);
  return distance(before, (await state()).navigation.position);
}
try {
  await page.goto(url);
  await ready();
  const initial = await state();
  await page.keyboard.down('ArrowRight');
  await page.waitForFunction(before => Math.hypot(...window.__MLB_DEBUG__.camera.map((v, i) => v - before[i])) > .5, initial.camera);
  await page.keyboard.up('ArrowRight');
  check('Arrow key pans camera and target', distance(initial.camera, (await state()).camera) > .5 && distance(initial.target, (await state()).target) > .5);
  await capture('arrow-pan');
  await page.locator('#reset').click();
  await ready();
  for (const size of [{ width: 1280, height: 900 }, { width: 768, height: 900 }, { width: 375, height: 812 }, { width: 844, height: 390 }]) {
    await page.setViewportSize(size);
    for (const [index, view] of ['diorama', 'exterior', 'interior', 'plan'].entries()) {
      await page.locator('.view-list button').nth(index).click();
      await ready();
      check(`${size.width} ${view} retained`, (await state()).view === view);
      const overlaps = await page.evaluate(() => {
        const toggle = document.querySelector('#walk-toggle').getBoundingClientRect();
        return ['.masthead p', '.destinations'].filter(selector => {
          const element = document.querySelector(selector);
          if (!element.getClientRects().length) return false;
          const rect = element.getBoundingClientRect();
          return Math.min(toggle.right, rect.right) > Math.max(toggle.left, rect.left) && Math.min(toggle.bottom, rect.bottom) > Math.max(toggle.top, rect.top);
        });
      });
      check(`${size.width} ${view} walking launcher does not cover text or navigation`, overlaps.length === 0, { overlaps });
      await capture(`${size.width}-explore-${view}`);
    }
    await page.locator('#reset').click();
    await ready();
    const before = await state();
    await page.locator('#walk-toggle').click();
    await page.waitForFunction(() => window.__MLB_DEBUG__.navigation.mode === 'walk');
    check(`${size.width} walk mode exposes model`, await page.locator('.destinations').isHidden() && await page.locator('#walk-controls').isVisible());
    check(`${size.width} no horizontal overflow`, !(await layout(page)).horizontalOverflow);
    await capture(`${size.width}-walk-start`);
    await ev.accessibility(page, `${size.width}-walk-day`);
    const start = (await state()).navigation.position;
    const startCamera = (await state()).camera;
    await page.keyboard.down('ArrowUp');
    await page.waitForFunction(before => Math.hypot(...window.__MLB_DEBUG__.navigation.position.map((v, i) => v - before[i])) >= .2, start);
    await capture(`${size.width}-walk-motion`);
    await page.keyboard.up('ArrowUp');
    await page.waitForFunction(() => !window.__MLB_DEBUG__.navigation.moving);
    const end = await state();
    check(`${size.width} following camera translates equally`, Math.abs(distance(startCamera, end.camera) - distance(start, end.navigation.position)) < .01);
    await page.locator('#night').click();
    await capture(`${size.width}-walk-night`);
    await ev.accessibility(page, `${size.width}-walk-night`);
    await page.locator('#ceiling').click();
    await capture(`${size.width}-walk-ceiling-open`);
    await page.locator('#reference').click();
    await page.locator('#source-image').evaluate(image => image.decode());
    await capture(`${size.width}-walk-reference`);
    const stopped = (await state()).navigation.position;
    await page.keyboard.down('ArrowUp');
    await page.waitForTimeout(300);
    await page.keyboard.up('ArrowUp');
    check(`${size.width} modal suppresses movement`, distance(stopped, (await state()).navigation.position) < .001);
    await page.keyboard.press('Escape');
    check(`${size.width} modal Escape preserves walking`, (await state()).navigation.mode === 'walk');
    await page.keyboard.press('Escape');
    const restored = await state();
    check(`${size.width} Escape restores original camera`, restored.navigation.mode === 'explore' && distance(restored.camera, before.camera) < .02);
    await capture(`${size.width}-walk-exit`);
    await page.locator('#reset').click();
    await ready();
  }
  await page.setViewportSize({ width: 1280, height: 900 });
  await ready();
  await page.locator('#walk-toggle').click();
  for (const key of ['ArrowUp', 'ArrowDown', 'ArrowLeft', 'ArrowRight', 'w', 's', 'a', 'd']) check(`Walking ${key} input`, await move(key) >= .15);
  const beforeCamera = (await state()).camera;
  const beforePosition = (await state()).navigation.position;
  await move('ArrowUp', .3);
  const following = await state();
  check('Third-person camera follows actual visitor displacement', Math.abs(distance(beforeCamera, following.camera) - distance(beforePosition, following.navigation.position)) < .01);
  await capture('following-camera');
  await page.keyboard.down('ArrowUp');
  await page.evaluate(() => window.dispatchEvent(new Event('blur')));
  await page.waitForFunction(() => !window.__MLB_DEBUG__.navigation.moving);
  const paused = (await state()).navigation.position;
  await page.waitForTimeout(250);
  check('Blur event clears held movement', distance(paused, (await state()).navigation.position) < .001);
  await page.keyboard.up('ArrowUp');
  await page.locator('#walk-toggle').click();
  await page.locator('#walk-toggle').click();
  await page.keyboard.down('ArrowDown');
  await page.waitForTimeout(2500);
  const blocked = (await state()).navigation.position;
  await page.waitForTimeout(500);
  const blockedAfter = (await state()).navigation.position;
  await page.keyboard.up('ArrowDown');
  check('Boundary blocks outward travel while permitting wall sliding', blockedAfter[0] >= .5 && blockedAfter[2] <= 15.4 && Math.abs(blocked[0] - blockedAfter[0]) < .02, { blockedAfter });
  check('Close wall uses an interior first-person camera', (await state()).navigation.perspective === 'first-person' && (await state()).camera[0] >= .5);
  await capture('collision-stop');
  await page.locator('#walk-toggle').click();
  await page.locator('#walk-toggle').click();
  const touchBefore = (await state()).navigation.position;
  const upButton = await page.locator('[data-direction="ArrowUp"]').boundingBox();
  assert.ok(upButton);
  await page.mouse.move(upButton.x + upButton.width / 2, upButton.y + upButton.height / 2);
  await page.mouse.down();
  await page.waitForFunction(before => Math.hypot(...window.__MLB_DEBUG__.navigation.position.map((v, i) => v - before[i])) > .15, touchBefore);
  await capture('direction-pad-held');
  await page.mouse.up();
  await page.waitForFunction(() => !window.__MLB_DEBUG__.navigation.moving);
  check('On-screen held direction control moves and releases', distance(touchBefore, (await state()).navigation.position) > .15);
  await page.setViewportSize({ width: 375, height: 812 });
  await capture('orientation-walk');
  await page.locator('#walk-toggle').click();
  await capture('orientation-exit');
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.locator('#walk-toggle').click();
  await move('ArrowUp');
  await capture('reduced-motion-walk');
  check('Reduced motion retains intentional movement', (await state()).navigation.mode === 'walk');
  await page.emulateMedia({ reducedMotion: 'no-preference' });
  await page.evaluate(() => { window.__walkLifecycle = { id: Math.random(), restored: false }; addEventListener('pageshow', event => { if (event.persisted) window.__walkLifecycle.restored = true; }); });
  const id = await page.evaluate(() => window.__walkLifecycle.id);
  await page.goto('http://localhost:4175/sources/plan.png');
  await page.goBack({ waitUntil: 'commit' });
  await ready();
  check('Walk mode survives real BFCache restoration', await page.evaluate(id => window.__walkLifecycle.id === id && window.__walkLifecycle.restored && window.__MLB_DEBUG__.navigation.mode === 'walk', id));
  await move('ArrowUp');
  await capture('bfcache-walk');
  await page.keyboard.press('Escape');
  await page.locator('#reset').click();
  await ready();
  check('Reset still selects diorama after walking', (await state()).view === 'diorama');
  check('No JavaScript errors', ev.report.errors.length === 0);
  check('No accessibility violations', ev.report.accessibility.every(audit => audit.violations.length === 0));
} catch (error) {
  ev.report.failure = String(error);
  await capture('failure');
  process.exitCode = 1;
} finally {
  await browser.close();
  await ev.finish();
  console.log(JSON.stringify({ checks: ev.report.checks.length, captures: ev.report.captures.length, failure: ev.report.failure, errors: ev.report.errors, accessibility: ev.report.accessibility, sourceStable: ev.report.sourceStable }));
}
