import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import * as THREE from 'three';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
const bytes = await readFile('public/assets/visitor.glb');
const gltf = await new GLTFLoader().parseAsync(Uint8Array.from(bytes).buffer, '');
const bounds = new THREE.Box3().setFromObject(gltf.scene);
assert.ok(Math.abs(bounds.min.y) < .001, 'Asset soles rest on ground');
assert.ok(bounds.max.y > 1.8 && bounds.max.y < 1.9, 'Asset has human-scale height');
const clip = gltf.animations.find(animation => animation.name === 'Walk');
assert.ok(clip && clip.tracks.length === 8, 'Walk clip animates all eight limb joints');
const hip = gltf.scene.getObjectByName('hip--1');
assert.ok(hip, 'Articulated hip joint remains independently addressable');
const rest = hip.quaternion.clone();
const mixer = new THREE.AnimationMixer(gltf.scene);
mixer.clipAction(clip).play();
mixer.setTime(.2);
assert.ok(hip.quaternion.angleTo(rest) > .3, 'Loaded GLB animation actually moves hip');
console.log(JSON.stringify({ bytes: bytes.length, height: bounds.max.y, animations: gltf.animations.map(animation => animation.name), animatedJoints: clip.tracks.length, status: 'passed' }));
